spring:
  r2dbc:
    url: r2dbc:h2:mem:///treasury?options=DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
  h2:
    console:
      enabled: true
  graphql:
    graphiql:
      enabled: true
      path: /graphiql

logging:
  level:
    org.springframework.r2dbc: DEBUG
    io.r2dbc.h2: DEBUG

server:
  port: 8080
