package com.example.treasury.config;

import org.springframework.context.annotation.Configuration;
import org.springframework.context.event.EventListener;
import org.springframework.r2dbc.core.DatabaseClient;
import org.springframework.boot.context.event.ApplicationReadyEvent;
import lombok.RequiredArgsConstructor;

@Configuration
@RequiredArgsConstructor
public class DatabaseInit {

  private final DatabaseClient client;

  @EventListener(ApplicationReadyEvent.class)
  public void init() {
    client.sql("""
      CREATE TABLE IF NOT EXISTS orders (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        term VARCHAR(10) NOT NULL,
        amount DECIMAL(19,2) NOT NULL,
        created_at TIMESTAMP NOT NULL,
        status VARCHAR(20) NOT NULL,
        rate_at_submission DOUBLE
      )
    """).fetch().rowsUpdated().block();
  }
}
